version: '3.8'

services:
  app:
    image: filmbase
    build:
      context: .
      dockerfile: example.Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/filmbase
      SPRING_DATASOURCE_USERNAME:
      SPRING_DATASOURCE_PASSWORD:
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: filmbase
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    ports:
      - "5432:5432"